apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfr
  template:
    metadata:
      labels:
        app: gtfr
    spec:
      containers:
      - image: okteto.dev/gtfr:latest
        name: gtfr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a98404c4-7083-4d17-972c-053b845c99bd"
        - name: Vless_Path
          value: "/vxfd65tgfrjhyt"
        - name: Vmess_UUID
          value: "a98404c4-7083-4d17-972c-053b845c99bd"
        - name: Vmess_Path
          value: "/gdb5tgfr4dsew"
        - name: Share_Path
          value: "/v2link"
